### ISSUE TITLE
Service gridboxconnector exited with code 1 (by signal 0)

### ISSUE THREAD

**Issue by Bollgarbop** [unl0ck/homeassistant-addon-viessmann-gridbox#32]
### Describe the bug what do have

addon stops to work basicly direct after start. happens since update to 2.5.7
wait time seems not to affect that. 

happens on HAOS
Core 2024.5.5
Supervisor 2024.05.1
Operating System 12.3
Frontend 20240501.1

### Log details

```text
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service gridboxconnector: starting
s6-rc: info: service gridboxconnector successfully started
s6-rc: info: service legacy-services: starting
[12:08:25] INFO: Starting GridboxConnector...
s6-rc: info: service legacy-services successfully started
total 12K    
     4 drwxr-xr-x    2 root     root        4.0K Jun  2 12:08 .
     4 drwxr-xr-x    1 root     root        4.0K Jun  2 12:08 ..
     4 -rw-------    1 root     root          94 Jun  2 12:08 options.json
{
  "username": "user@user.com",
  "password": "pw",
  "wait_time": 60
}total 16K    
     4 drwxr-xr-x    1 root     root        4.0K Jun  1 05:32 .
     4 drwxr-xr-x    1 root     root        4.0K Jun  2 12:08 ..
     4 drwxr-xr-x    3 root     root        4.0K Jun  1 05:31 GridboxConnector
     4 -rw-r--r--    1 root     root         494 Jun  1 05:31 cloudSettings.json
/build
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/build/GridboxConnector/__main__.py", line 12, in <module>
    logger.setLevel(logging.getLevelName(os.getenv('LOG_LEVEL', 'INFO')))
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1452, in setLevel
    self.level = _checkLevel(level)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 198, in _checkLevel
    raise ValueError("Unknown level: %r" % level)
ValueError: Unknown level: 'Level null'
[12:08:25] INFO: Service gridboxconnector exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service gridboxconnector: stopping
s6-rc: info: service gridboxconnector successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service gridboxconnector: starting
s6-rc: info: service gridboxconnector successfully started
s6-rc: info: service legacy-services: starting
[12:13:46] INFO: Starting GridboxConnector...
s6-rc: info: service legacy-services successfully started
total 12K    
     4 drwxr-xr-x    2 root     root        4.0K Jun  2 12:13 .
     4 drwxr-xr-x    1 root     root        4.0K Jun  2 12:13 ..
     4 -rw-------    1 root     root          95 Jun  2 12:13 options.json
{
  "username": "user@user.com",
  "password": "pw",
  "wait_time": 180
}total 16K    
     4 drwxr-xr-x    1 root     root        4.0K Jun  1 05:32 .
     4 drwxr-xr-x    1 root     root        4.0K Jun  2 12:13 ..
     4 drwxr-xr-x    3 root     root        4.0K Jun  1 05:31 GridboxConnector
     4 -rw-r--r--    1 root     root         494 Jun  1 05:31 cloudSettings.json
/build
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/build/GridboxConnector/__main__.py", line 12, in <module>
    logger.setLevel(logging.getLevelName(os.getenv('LOG_LEVEL', 'INFO')))
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1452, in setLevel
    self.level = _checkLevel(level)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 198, in _checkLevel
    raise ValueError("Unknown level: %r" % level)
ValueError: Unknown level: 'Level null'
[12:13:47] INFO: Service gridboxconnector exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service gridboxconnector: stopping
s6-rc: info: service gridboxconnector successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Version

2.5.7

**Comment by unl0ck** [comment]
should fixed in 2.5.8
