### ISSUE TITLE
Wert von "Heizung" wird nicht in HA ausgegeben

### ISSUE THREAD

**Issue by Lendelfinger** [unl0ck/homeassistant-addon-viessmann-gridbox#35]
### Describe the bug what do have

Ich habe in meiner Gridbox auf der rechten Seite die Werte "Heizung" (nicht "Wärmepumpe") und "Haushaltverbrauch". Der Wert von "Haushaltsverbrauch" wird auch regelmäßig in HA abgebildet. Der Wert von "Heizung" wird leider nicht als Entität abgebildet. Ist dies ein Fehler oder kann man durch Änderung einer Einstellung diese Werte auch einbinden?
![Unbenannt](https://github.com/unl0ck/homeassistant-addon-viessmann-gridbox/assets/129831637/c7d4d659-9970-4c2b-9704-cc371e0633a6)

### Log details

```text
4 drwxr-xr-x    2 root     root        4.0K Jul  8 16:37 .
     4 drwxr-xr-x    1 root     root        4.0K Jul  8 16:37 ..
     4 -rw-------    1 root     root         114 Jul  8 16:37 options.json
{
  "username": "XXX",
  "password": "XXX",
  "wait_time": 30,
  "log_level": "INFO"
}total 16K    
     4 drwxr-xr-x    1 root     root        4.0K Jun  6 19:54 .
     4 drwxr-xr-x    1 root     root        4.0K Jul  8 16:37 ..
     4 drwxr-xr-x    3 root     root        4.0K Jun  6 19:53 GridboxConnector
     4 -rw-r--r--    1 root     root         494 Jun  6 19:53 cloudSettings.json
/build
2024-07-08 16:37:19,726 __main__.py:57 INFO - {'batteries': [{'applianceID': 'a1731af4-0399-495b-92c2-523fd61ab681', 'capacity': 10000, 'nominalCapacity': 10000, 'power': 0, 'remainingCharge': 10000, 'stateOfCharge': 1}], 'battery': {'capacity': 10000, 'nominalCapacity': 10000, 'power': 0, 'remainingCharge': 10000, 'stateOfCharge': 1}, 'consumption': 1709, 'directConsumption': 1709, 'directConsumptionEV': 0, 'directConsumptionHeatPump': 0, 'directConsumptionHeater': 0, 'directConsumptionHousehold': 1709, 'directConsumptionRate': 0.29049804521502637, 'grid': -4174, 'gridMeterReadingNegative': 5358600000, 'gridMeterReadingPositive': 5335920000, 'heaters': [{'applianceID': '12bdd8ec-9b1e-465e-8f26-feae00e5af0f', 'power': 0, 'temperature': 72.5}], 'heating': 0, 'measuredAt': '2024-07-08T14:37:19Z', 'photovoltaic': 5883, 'production': 5883, 'selfConsumption': 1709, 'selfConsumptionRate': 0.29049804521502637, 'selfSufficiencyRate': 1, 'selfSupply': 1709, 'totalConsumption': 1709}
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service gridboxconnector: stopping
[17:07:46] INFO: Service gridboxconnector exited with code 256 (by signal 15)
s6-rc: info: service gridboxconnector successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service gridboxconnector: starting
s6-rc: info: service gridboxconnector successfully started
s6-rc: info: service legacy-services: starting
[17:07:52] INFO: Starting GridboxConnector...
s6-rc: info: service legacy-services successfully started
total 12K    
     4 drwxr-xr-x    2 root     root        4.0K Jul  8 17:07 .
     4 drwxr-xr-x    1 root     root        4.0K Jul  8 17:07 ..
     4 -rw-------    1 root     root         113 Jul  8 17:07 options.json
{
  "username": "XXX",
  "password": "XXX",
  "wait_time": 5,
  "log_level": "INFO"
}total 16K    
     4 drwxr-xr-x    1 root     root        4.0K Jun  6 19:54 .
     4 drwxr-xr-x    1 root     root        4.0K Jul  8 17:07 ..
     4 drwxr-xr-x    3 root     root        4.0K Jun  6 19:53 GridboxConnector
     4 -rw-r--r--    1 root     root         494 Jun  6 19:53 cloudSettings.json
/build
2024-07-08 17:07:56,481 __main__.py:57 INFO - {'batteries': [{'applianceID': 'a1731af4-0399-495b-92c2-523fd61ab681', 'capacity': 10000, 'nominalCapacity': 10000, 'power': 179, 'remainingCharge': 10000, 'stateOfCharge': 1}], 'battery': {'capacity': 10000, 'nominalCapacity': 10000, 'power': 179, 'remainingCharge': 10000, 'stateOfCharge': 1}, 'consumption': 2073.5, 'directConsumption': 5601.5, 'directConsumptionEV': 0, 'directConsumptionHeatPump': 0, 'directConsumptionHeater': 3709, 'directConsumptionHousehold': 1892.5, 'directConsumptionRate': 1, 'grid': 2, 'gridMeterReadingNegative': 5364000000, 'gridMeterReadingPositive': 5335920000, 'heaters': [{'applianceID': '12bdd8ec-9b1e-465e-8f26-feae00e5af0f', 'power': 3709, 'temperature': 71.8}], 'heating': 3709, 'measuredAt': '2024-07-08T15:07:55Z', 'photovoltaic': 5601.5, 'production': 5601.5, 'selfConsumption': 5601.5, 'selfConsumptionRate': 1, 'selfSufficiencyRate': 0.9996541288370082, 'selfSupply': 5780.5, 'totalConsumption': 5782.5}
2024-07-09 03:07:59,658 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Status Code 401
2024-07-09 03:07:59,659 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Response {}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/build/GridboxConnector/__main__.py", line 54, in <module>
    result = measurement[0]
IndexError: list index out of range
[03:07:59] INFO: Service gridboxconnector exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service gridboxconnector: stopping
s6-rc: info: service gridboxconnector successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service gridboxconnector: starting
s6-rc: info: service gridboxconnector successfully started
s6-rc: info: service legacy-services: starting
[03:08:06] INFO: Starting GridboxConnector...
s6-rc: info: service legacy-services successfully started
total 12K    
     4 drwxr-xr-x    2 root     root        4.0K Jul  9 03:08 .
     4 drwxr-xr-x    1 root     root        4.0K Jul  9 03:08 ..
     4 -rw-------    1 root     root         113 Jul  9 03:08 options.json
{
  "username": "XXX",
  "password": "XXX",
  "wait_time": 5,
  "log_level": "INFO"
}total 16K    
     4 drwxr-xr-x    1 root     root        4.0K Jun  6 19:54 .
     4 drwxr-xr-x    1 root     root        4.0K Jul  9 03:08 ..
     4 drwxr-xr-x    3 root     root        4.0K Jun  6 19:53 GridboxConnector
     4 -rw-r--r--    1 root     root         494 Jun  6 19:53 cloudSettings.json
/build
2024-07-09 03:08:10,292 __main__.py:57 INFO - {'batteries': [{'applianceID': 'a1731af4-0399-495b-92c2-523fd61ab681', 'capacity': 10000, 'nominalCapacity': 10000, 'power': 538, 'remainingCharge': 5400, 'stateOfCharge': 0.54}], 'battery': {'capacity': 10000, 'nominalCapacity': 10000, 'power': 538, 'remainingCharge': 5400, 'stateOfCharge': 0.54}, 'consumption': 543, 'directConsumption': 0, 'directConsumptionEV': 0, 'directConsumptionHeatPump': 0, 'directConsumptionHeater': 0, 'directConsumptionHousehold': 0, 'grid': 5, 'gridMeterReadingNegative': 5374800000, 'gridMeterReadingPositive': 5337000000, 'heaters': [{'applianceID': '12bdd8ec-9b1e-465e-8f26-feae00e5af0f', 'power': 0, 'temperature': 49.5}], 'heating': 0, 'measuredAt': '2024-07-09T01:08:09Z', 'photovoltaic': 0, 'production': 0, 'selfConsumption': 0, 'selfSufficiencyRate': 0.990791896869245, 'selfSupply': 538, 'totalConsumption': 543}
```

### Version

2.6.3

**Comment by unl0ck** [comment]
ich hatte noch keinen der ne Heizung angeschlossen hatte, werde das noch nachträglich einbauen, vielen dank für den log damit lässt sich einiges anfangen.

**Comment by unl0ck** [comment]
auch schön zu sehen, dass ich ne exception habe und er automatisch neustartet ;) 

aber kannst du mir einmal nen log schicken wo auch die heizung nen verbrauch hat? in den logs jetzt sieht man das nicht.

**Comment by unl0ck** [comment]
hab auf edge erst einmal nur verbrauch der heizung eingebaut, kannst du das mal testen?

**Comment by Lendelfinger** [comment]
Funktioniert leider nicht richtig, kurz nach dem Starten wird das Addon wieder gestoppt.

}total 16K    
   4.0K drwxr-xr-x    1 root     root        4.0K Jul  9 14:16 .
   4.0K drwxr-xr-x    1 root     root        4.0K Jul  9 15:59 ..
   4.0K drwxr-xr-x    3 root     root        4.0K Jul  9 14:15 GridboxConnector
   4.0K -rw-r--r--    1 root     root         494 Jul  9 14:15 cloudSettings.json
/build
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/build/GridboxConnector/__main__.py", line 31, in <module>
    options_json = json.load(options_file)
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
                 ^^^^^^^
AttributeError: 'str' object has no attribute 'read'
[16:00:03] INFO: Service gridboxconnector exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service gridboxconnector: stopping
s6-rc: info: service gridboxconnector successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
-----------------------------------------------------------

 Add-on: Viessmann Gridbox Connector (edge)
 Viessmann Gridbox Connector (edge)
-----------------------------------------------------------
 Add-on version: 2.7.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 12.4  (aarch64 / yellow)
 Home Assistant Core: 2024.7.1
 Home Assistant Supervisor: 2024.06.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
Log level is set to INFO
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service gridboxconnector: starting
s6-rc: info: service gridboxconnector successfully started
s6-rc: info: service legacy-services: starting
[16:00:48] INFO: Starting GridboxConnector...
s6-rc: info: service legacy-services successfully started
total 12K    
   4.0K drwxr-xr-x    2 root     root        4.0K Jul  9 16:00 .
   4.0K drwxr-xr-x    1 root     root        4.0K Jul  9 16:00 ..
   4.0K -rw-------    1 root     root         114 Jul  9 16:00 options.json
{
  "username": "XXX",
  "password": "XXX",
  "wait_time": 10,
  "log_level": "INFO"
}total 16K    
   4.0K drwxr-xr-x    1 root     root        4.0K Jul  9 14:16 .
   4.0K drwxr-xr-x    1 root     root        4.0K Jul  9 16:00 ..
   4.0K drwxr-xr-x    3 root     root        4.0K Jul  9 14:15 GridboxConnector
   4.0K -rw-r--r--    1 root     root         494 Jul  9 14:15 cloudSettings.json
/build
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/build/GridboxConnector/__main__.py", line 31, in <module>
    options_json = json.load(options_file)
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
                 ^^^^^^^
AttributeError: 'str' object has no attribute 'read'
[16:00:51] INFO: Service gridboxconnector exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service gridboxconnector: stopping
s6-rc: info: service gridboxconnector successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by unl0ck** [comment]
Danke für den Test sorry für den Fehler dann Bau ich das morgen oder heute Nacht um.

**Comment by unl0ck** [comment]
2.7.3 @Lendelfinger sollte nun klappen

**Comment by Lendelfinger** [comment]
Habe es installiert und läuft momentan stabil. Werde morgen bzw. übermorgen nochmal berichten.
Vielen Dank. Toller Support.

**Comment by unl0ck** [comment]
alles klar, wenn das soweit passt, dann kommt das auf stable. danke fürs feedback

**Comment by Lendelfinger** [comment]
Hat heute Morgen gestoppt beim ersten Blick über den Browser (Chrome) in HA.

`2024-07-11 08:40:32,704 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Response {}
2024-07-11 08:40:32,798 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Status Code 401
2024-07-11 08:40:32,799 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Response {}
2024-07-11 08:40:32,898 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Status Code 401
2024-07-11 08:40:32,898 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Response {}
2024-07-11 08:40:32,994 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Status Code 401
2024-07-11 08:40:32,994 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Response {}
2024-07-11 08:40:33,094 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Status Code 401
2024-07-11 08:40:33,095 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Response {}
2024-07-11 08:40:33,197 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Status Code 401
2024-07-11 08:40:33,198 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Response {}
2024-07-11 08:40:33,284 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Status Code 401
2024-07-11 08:40:33,285 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Response {}
2024-07-11 08:40:33,380 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Status Code 401
2024-07-11 08:40:33,381 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Response {}
2024-07-11 08:40:33,484 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Status Code 401
2024-07-11 08:40:33,485 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Response {}
2024-07-11 08:40:33,576 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Status Code 401
2024-07-11 08:40:33,576 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Response {}
2024-07-11 08:40:33,662 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Status Code 401
2024-07-11 08:40:33,663 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Response {}
2024-07-11 08:40:33,753 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Status Code 401
2024-07-11 08:40:33,753 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Response {}
2024-07-11 08:40:33,857 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Status Code 401
2024-07-11 08:40:33,858 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Response {}
2024-07-11 08:40:33,943 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Status Code 401
2024-07-11 08:40:33,944 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Response {}
2024-07-11 08:40:34,025 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Status Code 401
2024-07-11 08:40:34,026 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Response {}
2024-07-11 08:40:34,155 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Status Code 401
2024-07-11 08:40:34,155 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Response {}
2024-07-11 08:40:34,241 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Status Code 401
2024-07-11 08:40:34,242 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Response {}
2024-07-11 08:40:34,337 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Status Code 401
2024-07-11 08:40:34,338 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Response {}
2024-07-11 08:40:34,433 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Status Code 401
2024-07-11 08:40:34,433 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Response {}
2024-07-11 08:40:34,547 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Status Code 401
2024-07-11 08:40:34,547 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Response {}
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service gridboxconnector: stopping
2024-07-11 08:40:34,645 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Status Code 401
2024-07-11 08:40:34,646 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Response {}
[08:40:34] INFO: Service gridboxconnector exited with code 256 (by signal 15)
s6-rc: info: service gridboxconnector successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting`

**Comment by unl0ck** [comment]
ist aber wieder angestartet oder ?
das ist schon mal das wichtigste, aber ich vermute, ich hab noch nicht zu 100% das Problem gelöst, wenn der Authentifizierungstoken abgelaufen ist, sich einen neuen holen reibungslos klappt, danke für das Feedback, ich bin nur immer wieder erstaunt, ich seh gar keine logs :D

**Comment by unl0ck** [comment]
@Lendelfinger hab jetzt mal 1.7.6 hoffentlich ne Entspannung in diesen von dir letzten Fehler reingebracht.
Wenn das so ist, dann würde ich beide Tickets schließen.

**Comment by Lendelfinger** [comment]
Hab jetzt mal das 2.7.6 Update eingespielt. 
Hatte gestern noch einige Abbrüche (mit der 2.7.5). Habe dann eine Automatisierung erstellt  wie bei Issue #21 erwähnt. 
Nachdem ich heute Morgen mal die Automatisierung gecheckt habe, ist sie heute Nacht bestimmt 10x aktiviert worden. 
Hab sie jetzt nach dem Update mal deaktiviert und werde berichten.

**Comment by unl0ck** [comment]
er hat sich nicht automatisch neu gestartet ?

**Comment by Lendelfinger** [comment]
Kann ich ehrlich gesagt nicht beurteilen. Ich hatte gestern im Laufe des Tages zweimal die Situation, dass die Werte im HA nicht aktualisiert wurden. Musste dann händisch neu starten, was auch sofort ging. 
Habe dann den Lösungsweg aus #21 gefunden und habe mich direkt daran gemacht, diese auch anzuwenden. Es könnte natürlich sein, dass die Automatisierung recht früh angesprungen ist, sprich: das Addon wäre evtl. von selbst neu gestartet die Automatiserung war aber schneller. Habe sie jetzt, wie gesagt, deaktiviert und werde berichten.

**Comment by unl0ck** [comment]
ich hab diese Probleme überhaupt nicht, das er anhält, ich hatte sie mal aber schon länger nemme,

**Comment by Lendelfinger** [comment]
Heute Morgen wieder mit folgender Meldung abgebrochen und manuell neugestartet:

`
2024-07-13 10:45:27,413 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Status Code 401
2024-07-13 10:45:27,413 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Response {}
2024-07-13 10:45:37,902 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Status Code 401
2024-07-13 10:45:37,902 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Response {}
2024-07-13 10:45:48,361 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Status Code 401
2024-07-13 10:45:48,362 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Response {}
2024-07-13 10:45:59,036 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Status Code 401
2024-07-13 10:45:59,036 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Response {}
2024-07-13 10:46:09,484 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Status Code 401
2024-07-13 10:46:09,485 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Response {}
2024-07-13 10:46:19,930 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Status Code 401
2024-07-13 10:46:19,931 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Response {}
2024-07-13 10:46:30,336 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Status Code 401
2024-07-13 10:46:30,337 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Response {}
2024-07-13 10:46:40,835 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Status Code 401
2024-07-13 10:46:40,835 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Response {}
2024-07-13 10:46:51,421 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Status Code 401
2024-07-13 10:46:51,421 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Response {}
2024-07-13 10:47:01,897 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Status Code 401
2024-07-13 10:47:01,898 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Response {}
2024-07-13 10:47:12,393 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Status Code 401
2024-07-13 10:47:12,394 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Response {}
2024-07-13 10:47:22,793 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Status Code 401
2024-07-13 10:47:22,793 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Response {}
2024-07-13 10:47:33,271 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Status Code 401
2024-07-13 10:47:33,272 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Response {}
2024-07-13 10:47:43,704 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Status Code 401
2024-07-13 10:47:43,705 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Response {}
2024-07-13 10:47:54,187 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Status Code 401
2024-07-13 10:47:54,188 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Response {}
2024-07-13 10:48:04,730 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Status Code 401
2024-07-13 10:48:04,731 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Response {}
2024-07-13 10:48:15,096 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Status Code 401
2024-07-13 10:48:15,097 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Response {}
2024-07-13 10:48:25,576 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Status Code 401
2024-07-13 10:48:25,576 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Response {}
2024-07-13 10:48:35,992 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Status Code 401
2024-07-13 10:48:35,993 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Response {}
2024-07-13 10:48:46,407 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Status Code 401
2024-07-13 10:48:46,408 - viessmann_gridbox_connector.GridboxConnector - WARNING - retrieve_live_data - Response {}
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service gridboxconnector: stopping
[10:48:48] INFO: Service gridboxconnector exited with code 256 (by signal 15)
s6-rc: info: service gridboxconnector successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

-----------------------------------------------------------
 Add-on: Viessmann Gridbox Connector (edge)
 Viessmann Gridbox Connector (edge)
-----------------------------------------------------------
 Add-on version: 2.7.6
 You are running the latest version of this add-on.
 System: Home Assistant OS 12.4  (aarch64 / yellow)
 Home Assistant Core: 2024.7.2
 Home Assistant Supervisor: 2024.06.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
Log level is set to INFO
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service gridboxconnector: starting
s6-rc: info: service gridboxconnector successfully started
s6-rc: info: service legacy-services: starting
[10:48:54] INFO: Starting GridboxConnector...
s6-rc: info: service legacy-services successfully started
total 12K    
   4.0K drwxr-xr-x    2 root     root        4.0K Jul 13 10:48 .
   4.0K drwxr-xr-x    1 root     root        4.0K Jul 13 10:48 ..
   4.0K -rw-------    1 root     root         114 Jul 13 10:48 options.json
{
  "username": "XXX",
  "password": "XXX",
  "wait_time": 10,
  "log_level": "INFO"
}total 16K    
   4.0K drwxr-xr-x    1 root     root        4.0K Jul 12 12:22 .
   4.0K drwxr-xr-x    1 root     root        4.0K Jul 13 10:48 ..
   4.0K drwxr-xr-x    3 root     root        4.0K Jul 12 12:21 GridboxConnector
   4.0K -rw-r--r--    1 root     root         494 Jul 12 12:21 cloudSettings.json
/build
2024-07-13 10:48:58,197 __main__.py:61 INFO - {'batteries': [{'applianceID': 'a1731af4-0399-495b-92c2-523fd61ab681', 'capacity': 10000, 'nominalCapacity': 10000, 'power': -126, 'remainingCharge': 9900, 'stateOfCharge': 0.99}], 'battery': {'capacity': 10000, 'nominalCapacity': 10000, 'power': -126, 'remainingCharge': 9900, 'stateOfCharge': 0.99}, 'consumption': 603, 'directConsumption': 3182, 'directConsumptionEV': 0, 'directConsumptionHeatPump': 0, 'directConsumptionHeater': 2579, 'directConsumptionHousehold': 603, 'directConsumptionRate': 0.9529799341120095, 'grid': -31, 'gridMeterReadingNegative': 5670000000, 'gridMeterReadingPositive': 5347080000, 'heaters': [{'applianceID': '12bdd8ec-9b1e-465e-8f26-feae00e5af0f', 'power': 2579, 'temperature': 57.6}], 'heating': 2579, 'l1CurtailmentPower': 0, 'l2CurtailmentPower': 0, 'l3CurtailmentPower': 0, 'measuredAt': '2024-07-13T08:48:57Z', 'photovoltaic': 3339, 'production': 3339, 'selfConsumption': 3308, 'selfConsumptionRate': 0.9907157831686133, 'selfSufficiencyRate': 1, 'selfSupply': 3182, 'totalConsumption': 3182}
`

**Comment by unl0ck** [comment]
Watchdog ist aber angeschaltet bei dir oder @Lendelfinger
