### ISSUE TITLE
Anfängerfrage: API-Lizenz notwendig?

### ISSUE THREAD

**Issue by DennisWeiser** [unl0ck/homeassistant-addon-viessmann-gridbox#42]
Hi!

Leider muss ich mal eine wahrscheinlich dumme Frage stellen, da ich gerade erst frisch begonnen habe mit HASS und dem Thema Smart Home:

Brauche ich eine Viessmann-API Zugang um dieses Add-on zu nutzen? 

Bekomme folgendes Protokoll ausgespuckt:

> s6-rc: info: service s6rc-oneshot-runner successfully stopped
> s6-rc: info: service s6rc-oneshot-runner: starting
> s6-rc: info: service s6rc-oneshot-runner successfully started
> s6-rc: info: service fix-attrs: starting
> s6-rc: info: service fix-attrs successfully started
> s6-rc: info: service legacy-cont-init: starting
> s6-rc: info: service legacy-cont-init successfully started
> s6-rc: info: service gridboxconnector: starting
> s6-rc: info: service gridboxconnector successfully started
> s6-rc: info: service legacy-services: starting
> [15:48:09] INFO: Starting GridboxConnector...
> s6-rc: info: service legacy-services successfully started
> **[15:48:09] ERROR: Got unexpected response from the API: Service not enabled**
> total 12K    
>      4 drwxr-xr-x    2 root     root        4.0K Jul 12 15:48 .
>      4 drwxr-xr-x    1 root     root        4.0K Jul 12 15:48 ..
>      4 -rw-------    1 root     root         115 Jul 12 15:48 options.json
> {
>   "username": "XXXXX",
>   "password": "YYYYY",
>   "wait_time": 60,
>   "log_level": "TRACE"
> }total 16K    
>      4 drwxr-xr-x    1 root     root        4.0K Jun  6 19:54 .
>      4 drwxr-xr-x    1 root     root        4.0K Jul 12 15:48 ..
>      4 drwxr-xr-x    3 root     root        4.0K Jun  6 19:53 GridboxConnector
>      4 -rw-r--r--    1 root     root         494 Jun  6 19:53 cloudSettings.json
> /build
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "/build/GridboxConnector/__main__.py", line 12, in <module>
>     logger.setLevel(logging.getLevelName(os.getenv('LOG_LEVEL', 'INFO')))
>   File "/usr/local/lib/python3.10/logging/__init__.py", line 1452, in setLevel
>     self.level = _checkLevel(level)
>   File "/usr/local/lib/python3.10/logging/__init__.py", line 198, in _checkLevel
>     raise ValueError("Unknown level: %r" % level)
> ValueError: Unknown level: 'Level TRACE'
> [15:48:10] INFO: Service gridboxconnector exited with code 1 (by signal 0)
> s6-rc: info: service legacy-services: stopping
> s6-rc: info: service legacy-services successfully stopped
> s6-rc: info: service gridboxconnector: stopping
> s6-rc: info: service gridboxconnector successfully stopped
> s6-rc: info: service legacy-cont-init: stopping
> s6-rc: info: service legacy-cont-init successfully stopped
> s6-rc: info: service fix-attrs: stopping
> s6-rc: info: service fix-attrs successfully stopped
> s6-rc: info: service s6rc-oneshot-runner: stopping
> s6-rc: info: service s6rc-oneshot-runner successfully stopped
> s6-rc: info: service s6rc-oneshot-runner: starting
> s6-rc: info: service s6rc-oneshot-runner successfully started
> s6-rc: info: service fix-attrs: starting
> s6-rc: info: service fix-attrs successfully started
> s6-rc: info: service legacy-cont-init: starting
> s6-rc: info: service legacy-cont-init successfully started
> s6-rc: info: service gridboxconnector: starting
> s6-rc: info: service gridboxconnector successfully started
> s6-rc: info: service legacy-services: starting
> [15:48:41] INFO: Starting GridboxConnector...
> s6-rc: info: service legacy-services successfully started
> [15:48:42] ERROR: Got unexpected response from the API: Service not enabled
> total 12K    
>      4 drwxr-xr-x    2 root     root        4.0K Jul 12 15:48 .
>      4 drwxr-xr-x    1 root     root        4.0K Jul 12 15:48 ..
>      4 -rw-------    1 root     root         115 Jul 12 15:48 options.json
> {
>   "username": "XXXX",
>   "password": "YYYY",
>   "wait_time": 60,
>   "log_level": "TRACE"
> }total 16K    
>      4 drwxr-xr-x    1 root     root        4.0K Jun  6 19:54 .
>      4 drwxr-xr-x    1 root     root        4.0K Jul 12 15:48 ..
>      4 drwxr-xr-x    3 root     root        4.0K Jun  6 19:53 GridboxConnector
>      4 -rw-r--r--    1 root     root         494 Jun  6 19:53 cloudSettings.json
> /build
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "/build/GridboxConnector/__main__.py", line 12, in <module>
>     logger.setLevel(logging.getLevelName(os.getenv('LOG_LEVEL', 'INFO')))
>   File "/usr/local/lib/python3.10/logging/__init__.py", line 1452, in setLevel
>     self.level = _checkLevel(level)
>   File "/usr/local/lib/python3.10/logging/__init__.py", line 198, in _checkLevel
>     raise ValueError("Unknown level: %r" % level)
> ValueError: Unknown level: 'Level TRACE'
> [15:48:42] INFO: Service gridboxconnector exited with code 1 (by signal 0)
> s6-rc: info: service legacy-services: stopping
> s6-rc: info: service legacy-services successfully stopped
> s6-rc: info: service gridboxconnector: stopping
> s6-rc: info: service gridboxconnector successfully stopped
> s6-rc: info: service legacy-cont-init: stopping
> s6-rc: info: service legacy-cont-init successfully stopped
> s6-rc: info: service fix-attrs: stopping
> s6-rc: info: service fix-attrs successfully stopped
> s6-rc: info: service s6rc-oneshot-runner: stopping
> s6-rc: info: service s6rc-oneshot-runner successfully stopped

MQTT habe ich noch nicht eingerichtet (falls das von Belang ist). Auch das muss ich mir erstmal aneignen, wäre dann mein nächster Schritt gewesen.

Vielen Dank für das Projekt hier und für die Mühe!

**Comment by DennisWeiser** [comment]
OK, nachdem der MQTT-Broker läuft siehts besser aus.
